---
framework: jest

blocklist:
  - "src/api/traversing.spec.ts##$(...)##.add()##(element) honors document order when element occurs :##within the current selection"
  
preRun:
  command:
    - npm i

preMerge:
  pattern:
    - './src/**/*.spec.ts'

postMerge:
  pattern:
    - './src/**/*.spec.ts'

postRun:
  command:
    - node --version
version: 1.0
